FROM python:3.12.0-slim-bookworm 

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -yq \
        gcc \
        python3-dev \
        openssh-server

COPY ./requirements.txt /app/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir \
    -r /app/requirements.txt

RUN mkdir /var/run/sshd \
    && echo 'root:password' | chpasswd \
    && sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Start SSH daemon
COPY . /app/
CMD ["/usr/sbin/sshd", "-D"]